{
 "title": "Pocket Network Shannon Relayminer(s)",
 "description": "Monitors the relayminers instances within the Homelab Kubernetes environment",
 "time": { "from": "2025-06-30T01:10:32.297Z", "to": "2025-06-30T15:39:23.943Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Name",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\",created_by_name=~\".*relayminer.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Pocket Network Shannon Relayminer\n\nThis dashboard monitors the activity of one or multiple relayminers.\n\nTo report any issues, please [this page](https://github.com/eddyzags/pocket-network-helm-chart/issues)"
   }
  },
  {
   "title": "Container Image",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests/s",
   "type": "stat",
   "description": "Number of processed requests per second.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(relayminer_requests_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests/Responses",
   "type": "stat",
   "description": "Amount of processed relay requests and responses.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(relayminer_requests_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "stat",
   "description": "Percentage of processing errors",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(relayminer_requests_errors_total{pod=~\"${pod}\"}[5m])) or vector(0) / sum(increase(relayminer_requests_total{pod=~\"${pod}\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relays P95 Lantency",
   "type": "stat",
   "description": "The worst relay request duration in microseconds over the dynamic global range.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    relayminer_relay_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests and Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(relayminer_requests_success_total{pod=~\"${pod}\"}[5m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(increase(relayminer_requests_errors_total{pod=~\"${pod}\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Total number of errors requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(relayminer_requests_errors_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Total Number of Relays by Service",
   "type": "timeseries",
   "description": "Shows the total number of processed relays based on the dynamic range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_id) (increase(relayminer_requests_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Service",
   "type": "timeseries",
   "description": "Number of errors relays processed by the Service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(relayminer_requests_errors_total{service_id!=\"\"}[5m])) by (service_id)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "95th Percentile Relays Duration By Service",
   "type": "timeseries",
   "description": "service call duration for performance analysis",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, service_id) (\n    relayminer_service_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Request Sizes",
   "type": "timeseries",
   "description": "request size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    relayminer_request_size_bytes_bucket{\n      pod=~\"${pod}\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Responses Size",
   "type": "timeseries",
   "description": "responses size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    relayminer_response_size_bytes_bucket{\n      pod=~\"${pod}\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Computational Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[5m])) by (name)",
     "legendFormat": "Value"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"cpu\", container=\"relayminer\"}\n)\n",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"$pod\", resource=\"cpu\", container=\"relayminer\"}\n)\n",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Container Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"${pod}\"}) by (name)",
     "legendFormat": "Value"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{pod=~\"${pod}\", resource=\"memory\", container=\"relayminer\"}\n)\n",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{pod=~\"${pod}\", resource=\"memory\", container=\"relayminer\"}\n)\n",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Relays Median Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    relayminer_relay_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "75th Relays Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le) (\n    relayminer_relay_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Relays Median Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    relayminer_relay_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relays Median Latency by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, service_id) (\n    relayminer_service_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "75th Relays Latency by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le, service_id) (\n    relayminer_service_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Relays Latency by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, service_id) (\n    relayminer_service_duration_seconds_bucket{\n      pod=~\"${pod}\",\n      status_code=\"200\"\n    }\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "description": "Number of bytes send by the process over the network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(process_network_receive_bytes_total{pod=~\"${pod}\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "description": "Number of bytes send by the process over the network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(process_network_transmit_bytes_total{pod=~\"${pod}\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Heap In Use And Allocated",
   "type": "timeseries",
   "description": "Number of bytes in heap and currently in use.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Idle",
   "type": "timeseries",
   "description": "Number of heap bytes waiting to be used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Obtained",
   "type": "timeseries",
   "description": "Number of heap bytes obtained from the system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Released",
   "type": "timeseries",
   "description": "Number of heap bytes released to OS.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Objects Freed",
   "type": "timeseries",
   "description": "Total number of heap objects freed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(go_memstats_frees_total{pod=~\"${pod}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collector In Use",
   "type": "timeseries",
   "description": "Number of bytes used for garbage collection system metadata. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{pod=~\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "A summary of the wall-time pause (stop-the-world) duration in garbage collection cycles",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\", pod=~\"${pod}\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}