{{- if eq .Values.protocol "shannon"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 4 }}
data:
  config.yaml:
    {{ toYaml .Values.shannon.relayminer.config | nindent 4 }}
  client.toml: |
    broadcast-mode = "sync"
    chain-id = "{{ .Values.chainId }}"
    keyring-backend = "test"
    node = "{{ .Values.shannon.relayminer.config.pocket_node.tx_node_rpc_url }}"
    output = "text"
{{- end }}
