{{- if and (eq .Values.protocol "shannon") .Values.shannon.relayminer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 4 }}
data:
  config.yaml: |
    {{ toYaml .Values.shannon.relayminer.config | nindent 4 }}
  client.toml: |
    {{ .Values.shannon.relayminer.cosmossdk.clientConfig | nindent 4 }}
{{- end }}
{{- if and ( eq .Values.protocol "shannon" ) .Values.shannon.fullnode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-fullnode
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-fullnode" ) | nindent 4 }}
data:
  config.toml: |
    {{ .Values.shannon.fullnode.cometbft.config | nindent 4 }}
  app.toml: |
    {{ .Values.shannon.fullnode.cometbft.app | nindent 4 }}
{{- end }}
