{{- if and .Values.protocol "shannon" .Values.shannon.relayminer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 4 }}
spec:
  {{- if not .Values.shannon.relayminer.autoscaling.enabled }}
  replicas: {{ .Values.shannon.relayminer.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pocket-network.selectorLabels" (dict "root" . "nameSuffix" "shannon-relayminer") | nindent 6 }}
  template:
    metadata:
      {{- with .Values.shannon.relayminer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 8 }}
    spec:
      {{- with .Values.shannon.relayminer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.shannon.relayminer.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.shannon.relayminer.podSecurityContext | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-home
          image: busybox
          {{- with .Values.shannon.relayminer.initContainersSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |
              mkdir -p {{ .Values.workingDirectory }}/config
              mkdir -p {{ .Values.workingDirectory }}/keyring-test
          volumeMounts:
            - name: working-directory
              mountPath: {{ .Values.workingDirectory }}
      containers:
        - name: relayminer
          {{- with .Values.shannon.relayminer.containersSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.shannon.relayminer.image.repository }}:{{ .Values.shannon.relayminer.image.tag | default .Values.version }}"
          imagePullPolicy: {{ .Values.shannon.relayminer.image.pullPolicy }}
          {{- if .Values.shannon.relayminer.development.delve.enabled }}
          command: [ "/go/bin/dlv" ]
          args:
            - exec
            - --listen={{ .Values.shannon.relayminer.development.delve.addr }}
            - --headless={{ .Values.shannon.relayminer.development.delve.headless }}
            - --api-version={{ .Values.shannon.relayminer.development.delve.apiVersion }}
            {{- if .Values.shannon.relayminer.development.delve.acceptMulticlient }}
            - --accept-multiclient
            {{- end }}
            - /usr/local/bin/pocketd
            - --
          {{ else }}
          args:
          {{- end }}
            - "relayminer"
            - "--home={{ .Values.workingDirectory }}"
            - "--keyring-backend={{ .Values.shannon.relayminer.keyring.backend }}"
            - "--config={{ .Values.workingDirectory }}/config/config.yaml"
            - "--grpc-insecure={{ .Values.shannon.relayminer.grpcInsecure }}"
            - "--log_level={{ .Values.shannon.relayminer.telemetry.logs.level }}"
            - "--gas-adjustment={{ .Values.shannon.relayminer.gasAdjustment }}"
            - "--gas-prices={{ .Values.shannon.relayminer.gasPrices }}"
          ports: {{- include "pocket-network.utils.listenURLToPorts" (dict "config" .Values.shannon.relayminer.config "kind" "Deployment") | nindent 12 }}
            {{- if .Values.shannon.relayminer.config.metrics.enabled }}
            - name: metrics
              containerPort: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.metrics.addr }}
              protocol: TCP
            {{- end }}
            {{- if .Values.shannon.relayminer.config.ping.enabled }}
            - name: ping
              containerPort: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.metrics.addr }}
              protocol: TCP
            {{- end }}
            {{- if .Values.shannon.relayminer.config.pprof.enabled }}
            - name: pprof
              containerPort: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.pprof.addr }}
              protocol: TCP
            {{- end }}
          {{- if and .Values.shannon.relayminer.config.ping.enabled .Values.shannon.relayminer.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.ping.addr }}
              initialDelaySeconds: {{ .Values.shannon.relayminer.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.shannon.relayminer.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.shannon.relayminer.resources.preset.enabled }}
          resources: {{- include "pocket-network.shannon.preset" (dict "type" .Values.shannon.relayminer.resources.preset.name) | nindent 12 }}
          {{- else }}
          resources: {{- toYaml .Values.shannon.relayminer.resources.values | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.shannon.relayminer.keyring.secrets }}
            {{- $global := .Values }}
            {{- range .Values.shannon.relayminer.keyring.secrets }}
            {{- $name := .name }}
            {{- range .keyNames }}
            - name: keys-{{ $name }}
              mountPath: "{{ $global.workingDirectory }}/keyring-test/{{ . }}"
              subPath: "{{ . }}"
              readOnly: true
            {{- end }}
            {{- end }}
            {{- end }}
            - name: config
              mountPath: "{{ .Values.workingDirectory }}/config/config.yaml"
              subPath: "config.yaml"
            - name: config
              mountPath: "{{ .Values.workingDirectory }}/config/client.toml"
              subPath: "client.toml"
            - name: working-directory
              mountPath: {{ .Values.workingDirectory }}
          {{- with .Values.shannon.relayminer.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.shannon.relayminer.keyring.secrets }}
        {{- range .Values.shannon.relayminer.keyring.secrets }}
        - name: keys-{{ .name }}
          secret:
            secretName: {{ .name }}
        {{- end }}
        {{- end }}
        - name: config
          configMap:
            name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
        - name: working-directory
          emptyDir: {}
      {{- with .Values.shannon.relayminer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shannon.relayminer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shannon.relayminer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
