{{- if and (eq .Values.shannon.relayminer.autoscaling.enabled true) (eq .Values.protocol "shannon") .Values.shannon.relayminer.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  minReplicas: {{ .Values.shannon.relayminer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.shannon.relayminer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.shannon.relayminer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.shannon.relayminer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.shannon.relayminer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.shannon.relayminer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
