{{- $root := . }}
{{- if and (eq .Values.protocol "shannon") .Values.shannon.relayminer.enabled .Values.shannon.relayminer.ingress.enabled -}}
{{- if and .Values.shannon.relayminer.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.shannon.relayminer.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.shannon.relayminer.ingress.annotations "kubernetes.io/ingress.class" .Values.shannon.relayminer.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 4 }}
  {{- with .Values.shannon.relayminer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.shannon.relayminer.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.shannon.relayminer.ingress.className }}
  {{- end }}
  {{- if .Values.shannon.relayminer.ingress.tls }}
  tls:
    {{- range .Values.shannon.relayminer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.shannon.relayminer.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "pocket-network.fullname" $root }}-shannon-relayminer
                port:
                  number: {{ .backend.service.port.number }}
              {{- else }}
              serviceName: {{ include "pocket-network.fullname" .root }}-shannon-relayminer
              servicePort: {{ .backend.service.port.number }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if .Values.shannon.fullnode.ingress.enabled -}}
{{- if and .Values.shannon.fullnode.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.shannon.fullnode.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.shannon.fullnode.ingress.annotations "kubernetes.io/ingress.class" .Values.shannon.fullnode.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-fullnode
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-fullnode" ) | nindent 4 }}
  {{- with .Values.shannon.fullnode.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.shannon.fullnode.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.shannon.fullnode.ingress.className }}
  {{- end }}
  {{- if .Values.shannon.fullnode.ingress.tls }}
  tls:
    {{- range .Values.shannon.fullnode.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.shannon.fullnode.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "pocket-network.fullname" $root }}-shannon-fullnode
                port:
                  number: {{ .backend.service.port.number }}
              {{- else }}
              serviceName: {{ include "pocket-network.fullname" .root }}-shannon-fullnode
              servicePort: {{ .backend.service.port.number }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
