{{ if and (eq .Values.shannon.relayminer.prometheus.serviceMonitor.enabled true) (eq .Values.protocol "shannon") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pocket-network.selectorLabels" (dict "root" . "nameSuffix" "shannon-relayminer") | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
{{ end }}
