{{- if eq .Values.protocol "shannon" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket-network.fullname" . }}-relayminer
  labels:
    {{- include "pocket-network.labels" . | nindent 4 }}
    app.pocket.network/name: {{ include "pocket-network.fullname" . }}-relayminer
spec:
  type: {{ .Values.shannon.relayminer.service.type }}
  ports: {{- include "pocket-network.utils.listenURLToPorts" (dict "config" .Values.shannon.relayminer.config "kind" "Service") | nindent 4 }}
    - port: {{ .Values.shannon.relayminer.metrics.port }}
      targetPort: {{ .Values.shannon.relayminer.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    app.pocket.network/name: {{ include "pocket-network.fullname" . }}-relayminer
{{- end }}
