{{- if and (eq .Values.protocol "shannon") .Values.shannon.relayminer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-relayminer" ) | nindent 4 }}
spec:
  type: {{ .Values.shannon.relayminer.service.type }}
  ports: {{- include "pocket-network.utils.listenURLToPorts" (dict "config" .Values.shannon.relayminer.config "kind" "Service") | nindent 4 }}
    {{ if .Values.shannon.relayminer.config.metrics.enabled }}
    - port: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.metrics.addr }}
      targetPort: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.metrics.addr }}
      protocol: TCP
      name: metrics
    {{- end }}
    {{- if .Values.shannon.relayminer.config.pprof.enabled }}
    - port: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.pprof.addr }}
      targetPort: {{- include "pocket-network.utils.extractPort" .Values.shannon.relayminer.config.pprof.addr }}
      protocol: TCP
      name: pprof
    {{- end }}
  selector:
    app.pocket.network/name: {{ include "pocket-network.fullname" . }}-shannon-relayminer
{{- end }}
{{- if and (eq .Values.protocol "shannon") .Values.shannon.fullnode.enabled }}
{{- $config := .Values.shannon.fullnode.cometbft.config | fromToml }}
{{- $app := .Values.shannon.fullnode.cometbft.app | fromToml }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-fullnode-internal
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-fullnode" ) | nindent 4 }}
spec:
  type: {{ .Values.shannon.fullnode.service.local.type }}
  ports: 
    - port: {{- include "pocket-network.utils.extractPort" $config.rpc.laddr }}
      targetPort: {{- include "pocket-network.utils.extractPort" $config.rpc.laddr }}
      protocol: TCP
      name: config-rpc
    - port: {{- include "pocket-network.utils.extractPort" $config.proxy_app }}
      targetPort: {{- include "pocket-network.utils.extractPort" $config.proxy_app }}
      name: config-abci
    {{- if $config.rpc.grpc_laddr }}
    - port: {{- include "pocket-network.utils.extractPort" $config.rpc.grpc_laddr }}
      targetPort: {{- include "pocket-network.utils.extractPort" $config.rpc.grpc_laddr }}
      name: config-grpc
    {{- end }}
    - port: {{- include "pocket-network.utils.extractPort" $config.p2p.laddr }}
      targetPort: {{- include "pocket-network.utils.extractPort" $config.p2p.laddr }}
      name: config-p2p
    {{- if $config.instrumentation.prometheus }}
    - port: {{- include "pocket-network.utils.extractPort" $config.instrumentation.prometheus_listen_addr }}
      targetPort: {{- include "pocket-network.utils.extractPort" $config.instrumentation.prometheus_listen_addr }}
      name: config-prometheus
    {{- end }}
    {{- if $app.api.enable }}
    - port: {{- include "pocket-network.utils.extractPort" $app.api.address }}
      targetPort: {{- include "pocket-network.utils.extractPort" $app.api.address }}
      name: app-api
    {{- end }}
    {{- if $app.grpc.enable }}
    - port: {{- include "pocket-network.utils.extractPort" $app.grpc.address }}
      targetPort: {{- include "pocket-network.utils.extractPort" $app.grpc.address }}
      name: app-grpc
    {{- end }}
    {{- if (index $app "grpc-web" "enable") }}
    - port: {{- include "pocket-network.utils.extractPort" (index $app "grpc-web" "address") }}
      targetPort: {{- include "pocket-network.utils.extractPort" (index $app "grpc-web" "address") }}
      name: app-grpc-web
    {{- end }}
  selector:
    app.pocket.network/name: {{ include "pocket-network.fullname" . }}-shannon-fullnode
{{- if .Values.shannon.fullnode.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket-network.fullname" . }}-shannon-fullnode-external
  labels:
    {{- include "pocket-network.labels" (dict "root" . "nameSuffix" "shannon-fullnode" ) | nindent 4 }}
spec:
  type: {{ .Values.shannon.fullnode.service.external.type }}
  ports:
    - port: {{- include "pocket-network.utils.extractPort" $config.rpc.laddr }}
      targetPort: {{- include "pocket-network.utils.extractPort" $config.rpc.laddr }}
      nodePort: {{ .Values.shannon.fullnode.service.external.rpc.nodePort }}
    - port: {{- include "pocket-network.utils.extractPort" $config.p2p.laddr }}
      targetPort: {{- include "pocket-network.utils.extractPort" $config.p2p.laddr }}
      nodePort: {{ .Values.shannon.fullnode.service.external.p2p.nodePort }}
  selector:
    app.pocket.network/name: {{ include "pocket-network.fullname" . }}-shannon-fullnode
{{- end }}
{{- end }}
